kind: Namespace
apiVersion: v1
metadata:
  name: 3scale
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
## https://docs.redhat.com/en/documentation/red_hat_3scale_api_management/2.15/html-single/installing_red_hat_3scale_api_management/index#system-database-secret
kind: Secret
apiVersion: v1
metadata:
  name: system-database
  namespace: 3scale
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
  URL: "postgresql://postgresql:postgresql@postgresql.3scale-system-database.svc.cluster.local:5432/postgresql"
type: Opaque
---
## https://docs.redhat.com/en/documentation/red_hat_3scale_api_management/2.15/html-single/installing_red_hat_3scale_api_management/index#zync-database-secret
kind: Secret
apiVersion: v1
metadata:
  name: zync
  namespace: 3scale
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
    DATABASE_URL: "postgresql://postgresql:postgresql@postgresql.3scale-zync-database.svc.cluster.local:5432/zync_production"
    ZYNC_DATABASE_PASSWORD: postgresql
type: Opaque
