apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 3scale-deployment-nprd
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: 3scale-gitops
  destination:
    namespace: 3scale
    name: in-cluster
    server: ''
  source:
    path: 'nprd'
    repoURL: 'git@github.com:gilvansfilho/3scale-deployment.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - Replace=false
    - ApplyOutOfSyncOnly=true
    - PrunePropagationPolicy=foreground